---
title: "muRL"
pagetitle: "muRL — Ryan T. Moore"
toc: true
toc-location: right
toc-title: "On this page"
---

**muRL: Mailmerge using R, LaTeX, and the Web**\
Version 0.1-13\
Ryan T. Moore and Andrew Reeves\
Available as a [CRAN package](http://cran.r-project.org/web/packages/muRL/index.html).

`muRL` is an R package that provides mailmerge methods for reading spreadsheets of addresses and other relevant information, creating standardized but customizable letters, and mapping US ZIP codes, including the locations of recipients. It provides a method for parsing and processing HTML code from online job postings of the American Political Science Association (APSA eJobs). The many options associated with this functionality are described in detail in the `muRL` manual.

## Installation

To install the latest version on CRAN, open R and type:

```r
install.packages("muRL")
library(muRL)
```

To install the latest version (0.1-13) directly, download [the package tarball](/files/software/muRL_0.1-13.tar.gz) and follow the [tar.gz install instructions](install-targz.qmd).

## Some helpful documents

- Use `muRL` to produce high-quality letters using R and LaTeX. [PDF](/files/software/murlvignPS.pdf)
- Use `muRL` to scrape APSA eJobs HTML files to produce a spreadsheet of jobs to apply for. [PDF](/files/software/murlejobsPS.pdf)
- The full `muRL` manual. [PDF](http://cran.r-project.org/web/packages/muRL/muRL.pdf)
- How to get started with R (for beginners, 1 page). [PDF](/files/ht/htr.pdf)

## Citation

The peer-reviewed journal article describing `muRL` is

> Moore, Ryan T. and Andrew Reeves. "The Job Market's First Steps: Using Research Tools to Simplify the Process". *PS: Political Science & Politics*, 44(2):385–391, April 2011.

If you use this package, please cite the article. To cite the package, use

> Ryan T. Moore and Andrew Reeves (2023). muRL: Mailmerge using R, LaTeX, and the Web. R package version 0.1-13. <http://www.ryantmoore.org/software.muRL.html>

## Missing ZIP codes

If you find that some recipients do not appear on your recipient map, their ZIP codes may be missing from the Census file. If you have a ZIP code you would like included for plotting, please email the package maintainer with four pieces of information:

- the state in which the ZIP code is located,
- the ZIP code itself,
- the latitude of the ZIP code to six decimal places (such as 38.643248),
- and the longitude of the ZIP code to six decimal places (such as -75.611025).

Please also provide the city and any other information required to verify the latitude and longitude for inclusion. Thanks!

## Acknowledgements

Many thanks to [Sonia Gerstenfield](https://github.com/sgerstt) for solving a regular expression problem for version 0.1-11.

## Previous versions

[Full CHANGELOG](http://cran.r-project.org/web/packages/muRL/ChangeLog).

- 0.1-13 (22 August 2023)
- 0.1-12 (5 December 2019)
- 0.1-11 (13 June 2017)
- 0.1-10 (27 July 2015)
- 0.1-9 (23 August 2013)
- 0.1-8 (15 August 2013)
- 0.1-7 (28 August 2012)
- 0.1-6 (27 May 2011)
- 0.1-5 (25 August 2010)
- 0.1-4 (28 October 2009)
- 0.1-3 (18 October 2009)
- 0.1-2 (20 August 2009)
- 0.1-1 (17 July 2009)
